/* 
available
not available
*/
const products = [
    {
        "id": 1,
        "title": "Sticker pack #1",
        "category": "stickers",
        "price": 13.99,
        "banner": "./img/banners/pack-1-banner.png",
        "slide-1": "./img/product-slides/slide-1-pack-1.png",
        "slide-2": "./img/product-slides/slide-2-pack-1.png",
        "slide-3": "./img/product-slides/slide-3-pack-1.png",
        "description": "22 screen printed stickers",
        "status": "in stock",
        "new arrival": false,
        "best seller": false
    }, {
        "id": 2,
        "title": "Sticker pack #2",
        "category": "stickers",
        "price": 15.99,
        "banner": "./img/banners/pack-2-banner.png",
        "slide-1": "./img/product-slides/slide-1-pack-2.png",
        "slide-2": "./img/product-slides/slide-2-pack-2.png",
        "slide-3": "./img/product-slides/slide-3-pack-2.png",
        "description": "27 screen printed stickers",
        "status": "in stock",
        "new arrival": false,
        "best seller": false
    }, {
        "id": 3,
        "title": "Sticker pack #3",
        "category": "stickers",
        "price": 10.99,
        "banner": "./img/banners/pack-3-banner.png",
        "slide-1": "./img/product-slides/slide-1-pack-3.png",
        "slide-2": "./img/product-slides/slide-2-pack-3.png",
        "slide-3": "./img/product-slides/slide-3-pack-3.png",
        "description": "12 screen printed stickers",
        "status": "in stock",
        "new arrival": false,
        "best seller": false
    }, {
        "id": 4,
        "title": "Sticker pack #4",
        "category": "stickers",
        "price": 10.99,
        "banner": "./img/banners/pack-4-banner.png",
        "slide-1": "./img/product-slides/slide-1-pack-4.png",
        "slide-2": "./img/product-slides/slide-2-pack-4.png",
        "slide-3": "./img/product-slides/slide-3-pack-4.png",
        "description": "12 screen printed stickers",
        "status": "in stock",
        "new arrival": false,
        "best seller": false
    }, {
        "id": 5,
        "title": "Sticker pack #5",
        "category": "stickers",
        "price": 10.99,
        "banner": "./img/banners/pack-5-banner.png",
        "slide-1": "./img/product-slides/slide-1-pack-5.png",
        "slide-2": "./img/product-slides/slide-2-pack-5.png",
        "slide-3": "./img/product-slides/slide-3-pack-5.png",
        "description": "13 screen printed stickers",
        "status": "in stock",
        "new arrival": false,
        "best seller": false
    }, {
        "id": 6,
        "title": "Sticker pack #6",
        "category": "stickers",
        "price": 10.99,
        "banner": "./img/banners/pack-6-banner.png",
        "slide-1": "./img/product-slides/slide-1-pack-6.png",
        "slide-2": "./img/product-slides/slide-2-pack-6.png",
        "slide-3": "./img/product-slides/slide-3-pack-6.png",
        "description": "13 screen printed stickers",
        "status": "in stock",
        "new arrival": false,
        "best seller": false
    }, {
        "id": 7,
        "title": "Sticker pack #7",
        "category": "stickers",
        "price": 12.99,
        "banner": "./img/banners/pack-7-banner.png",
        "slide-1": "./img/product-slides/slide-1-pack-7.png",
        "slide-2": "./img/product-slides/slide-2-pack-7.png",
        "slide-3": "./img/product-slides/slide-3-pack-7.png",
        "description": "17 screen printed stickers",
        "status": "in stock",
        "new arrival": false,
        "best seller": false
    }, {
        "id": 8,
        "title": "Sticker pack #8",
        "category": "stickers",
        "price": 12.99,
        "banner": "./img/banners/pack-8-banner.png",
        "slide-1": "./img/product-slides/slide-1-pack-8.png",
        "slide-2": "./img/product-slides/slide-2-pack-8.png",
        "slide-3": "./img/product-slides/slide-3-pack-8.png",
        "description": "18 screen printed stickers",
        "status": "in stock",
        "new arrival": false,
        "best seller": false
    }, {
        "id": 9,
        "title": "Sticker pack #9",
        "category": "stickers",
        "price": 11.99,
        "banner": "./img/banners/pack-9-banner.png",
        "slide-1": "./img/product-slides/slide-1-pack-9.png",
        "slide-2": "./img/product-slides/slide-2-pack-9.png",
        "slide-3": "./img/product-slides/slide-3-pack-9.png",
        "description": "15 screen printed stickers",
        "status": "in stock",
        "new arrival": false,
        "best seller": false
    }, {
        "id": 10,
        "category": "stickers",
        "price": 11.99,
        "banner": "./img/banners/pack-10-banner.png",
        "slide-1": "./img/product-slides/slide-1-pack-10.png",
        "slide-2": "./img/product-slides/slide-2-pack-10.png",
        "slide-3": "./img/product-slides/slide-3-pack-10.png",
        "description": "16 screen printed stickers",
        "status": "in stock",
        "new arrival": false,
        "best seller": false
    }, {
        "id": 11,
        "title": "EXTRABOLD T-shirt",
        "category": "t-shirt",
        "price": 22.99,
        "banner": "./img/banners/t-shirt-banner.png",
        "slide-1": "./img/product-slides/t-shirt-black.png",
        "slide-2": "./img/product-slides/t-shirt-white.png",
        "description": "Organic round neck T-shirt",
        "status": "in stock",
        "new arrival": false,
        "best seller": false
    },
];